# UAT specific properties
application:
  consumer:
    bootstrap.servers: pkc-mvx01.us-east-2.aws.confluent.cloud:9092
    security.protocol: SASL_SSL
    sasl.mechanism: PLAIN
    sasl.jaas.config: ${SASL_JAAS_CONFIG}
    schema.registry.url: ${SCHEMA_REGISTRY_URL}